// <auto-generated />
using System;
using CodeFirstApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirstApp.Migrations
{
    [DbContext(typeof(StudentInfoDbContext))]
    [Migration("20260411105126_third")]
    partial class third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CodeFirstApp.Models.Student", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stuid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sid"));

                    b.Property<string>("adhaar")
                        .HasColumnType("varchar(15)")
                        .HasColumnName("stuadhaar");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date")
                        .HasColumnName("studob");

                    b.Property<string>("email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stuemail");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("stugen");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stuname");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("stuphone");

                    b.HasKey("sid");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
